apiVersion: v1
kind: PersistentVolume
metadata:
  name: openshift-registry-pv
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /nfs
    server: 192.168.123.100
  persistentVolumeReclaimPolicy: Retain

